apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: testinkiii-project
  namespace: argocd
spec:
  description: Project for testinkiii
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'